A bunch of component solver additions and updates
samfundev/KtaneTwitchPlays pull request #571
Opened 2021-09-10 04:55 UTC by eXish

- Reformatted sorting of component solvers to where if an author has at least 2 mods with a component solver built into TP they get their own folder
- Clarified in Needy RNG's help message about getting extra time on TP
- Fixed Strike/Solve's faulty autosolver
- Allowed for abbreviated commands on Simon Squawks
- Added an autosolver to Letter Keys
- Added component solvers for the following modules:
Triangle Buttons (Needy)
Cacti's Conundrum
Draw (Needy)
Over Kilo
Pink Arrows
Weekdays (Needy)
Rune Match I/II/III (Needies)
- Shims have been added for the following (most are for autosolvers but Colour Flash ES's fixes a TP issue it had):
Colorful Insanity
Colorful Madness
Colour Flash
Colour Flash ES
Colour Flash PL
Flash Memory
Periodic Table
Semaphore
Shapes And Bombs
Sueet Wall
Tangrams (Note that this shim is not built with TP atm since it has a couple bugs)
Vexillology
Wavetapping

2021-09-10 22:33 UTC, samfundev requested changes
Thanks for the PR, found some improvements.

2021-09-10 22:33 UTC, samfundev commented on TwitchPlaysAssembly/Src/ComponentSolvers/Modded/Shims/VexillologyShim.cs
> +			while ((edgework.GetTime() >= 60 && !edgework.GetFormattedTime().Contains(edgework.GetSerialNumberNumbers().Last().ToString()[0])) || (edgework.GetTime() < 60 && !edgework.GetFormattedTime().Remov
This felt too messy, so I tried my best to simplify it. Let me know if I made any mistakes.
```suggestion

		char[] digits = null;
		if (_component.GetValue<bool>("_ChadRomania"))
			digits = new[] { '0', '5' };
		else if (SubmitTime != 10)
			digits = new[] { SubmitTime.ToString()[0] };
		else
			digits = new[] { edgework.GetSerialNumberNumbers().Last().ToString()[0] };

		while (true)
		{
			var time = edgework.GetTime() >= 60 ? edgework.GetFormattedTime() : edgework.GetFormattedTime().Remove(2);
			if (digits.Any(time.Contains))
				break;

			yield return true;
		}

```

2021-09-11 03:37 UTC, eXish commented on TwitchPlaysAssembly/Src/ComponentSolvers/Modded/Shims/SemaphoreShim.cs
> +		}
Semaphore does not loop around so unfortunately no it cannot.

2021-09-11 20:47 UTC, samfundev approved these changes

2021-09-11 20:47 UTC, merged