A bunch of updates
samfundev/KtaneTwitchPlays pull request #590
Opened 2023-03-14 21:54 UTC by eXish

Added component solvers for:
- Flashing Cube
- The Crafting Table (needy)
- Forget Fractal
- Look, Look Away (Special implementation, TP automatically highlights and unhighlights modules on most commands and even the last module zoom but the module inputs everytime the module is unhighlighted. To remedy this the feature is disabled if the module is Look, Look Away.)
- Nokia
- perspective eggs
- Pong (Needy)
- Jackbox.TV

Added shims to give autosolvers to:
- Color Decoding
- Harmony Sequence/Co-op Harmony Sequence
- Safety Square
- Table Madness

Fixed broken autosolvers for:
- Eight Pages
- SI-HTS

Fixed being able to set values on the SQL modules while still viewing the goal.

Added the ability to change the displays on Free Password and Large Free Password.

2023-03-19 02:42 UTC, samfundev requested changes
I don't think I see anything wrong, but the code could be cleaner. If you want, I can go through and make these changes.

2023-03-19 02:42 UTC, samfundev commented on TwitchPlaysAssembly/Src/ComponentSolvers/Modded/Shims/Misc/TableMadnessShim.cs
> +public class TableMadnessShim : ComponentSolverShim
ReflectionComponentSolverShim could be used here and for other shims.

2023-03-19 02:42 UTC, samfundev commented on TwitchPlaysAssembly/Src/ComponentSolvers/Modded/Misc/PongComponentSolver.cs
> +public class PongComponentSolver : ComponentSolver
ReflectionComponentSolver could be used here.

2023-03-19 02:42 UTC, samfundev commented on TwitchPlaysAssembly/Src/ComponentSolvers/Modded/Misc/PongComponentSolver.cs
> +		if (split[0].EqualsAny("left", "l") && split[1].EqualsAny("top", "t"))
FirstOrWhole could be used:
```suggestion
		if (split[0].FirstOrWhole("left") && split[1].FirstOrWhole("top"))
```

2023-03-19 02:42 UTC, samfundev commented on TwitchPlaysAssembly/Src/Commands/ModuleCommands.cs
> +		IEnumerator defocusCoroutine = module.Bomb.Defocus(module.Selectable, module.FrontFace, abortHighlightIds.Contains(module.BombComponent.GetModuleID()) ? false : true);
GitHub won't let me make a suggestion, but I think this code could be significantly simplified:
```csharp
		bool select = !module.BombComponent.GetModuleID().EqualsAny("lookLookAway");
		IEnumerator focusCoroutine = module.Bomb.Focus(module.Selectable, module.FocusDistance, module.FrontFace, select);
		while (focusCoroutine.MoveNext())
			yield return focusCoroutine.Current;

		yield return new WaitForSeconds(0.5f);
		yield return yield is float delay ? new WaitForSecondsWithCancel(delay, false, module.Solver) : yield;
		if (CoroutineCanceller.ShouldCancel)
		{
			module.StartCoroutine(module.Bomb.Defocus(module.Selectable, module.FrontFace, select);
			yield break;
		}
		IEnumerator defocusCoroutine = module.Bomb.Defocus(module.Selectable, module.FrontFace, select);
```

2023-03-21 00:16 UTC, eXish commented
> I don't think I see anything wrong, but the code could be cleaner. If you want, I can go through and make these changes.

 All these look fine to me. If you could go through these changes whenever you are free that would be great.

2023-03-25 15:22 UTC, samfundev approved these changes

2023-03-25 15:22 UTC, merged