Add command for currently running mission
samfundev/KtaneTwitchPlays pull request #597
Opened 2023-07-13 07:38 UTC by Fang1217

Usage: `!status` or !mission`.

2023-07-13 16:01 UTC, samfundev requested changes
I think the code could be simplified, otherwise it's pretty good!

2023-07-13 16:52 UTC, Fang1217 commented on TwitchPlaysAssembly/Src/Commands/GameCommands.cs
> +		}
Yep, edited and tested.

2023-07-14 03:22 UTC, samfundev approved these changes

2023-07-14 03:23 UTC, samfundev commented
LGTM, merging!

2023-07-14 03:23 UTC, merged