QoL: Always show when a mod is zoomed/superzoomed.
samfundev/KtaneTwitchPlays pull request #598
Opened 2023-07-13 08:16 UTC by Fang1217

There is no disadvantage (such as time loss) and only provide better quality when (super)zooming at the correct side of the bomb.

2023-07-13 16:04 UTC, samfundev requested changes
One quick optimization, otherwise this sounds like a great change!

2023-07-13 16:04 UTC, samfundev commented on TwitchPlaysAssembly/Src/Commands/ModuleCommands.cs
> +				routine = Show(module, toYield);
Could we merge this with line 470?
```csharp
IEnumerator routine = Show(module, toYield);
```

2023-07-13 16:06 UTC, Fang1217 commented on TwitchPlaysAssembly/Src/Commands/ModuleCommands.cs
> +				routine = Show(module, toYield);
Yep, merged.

2023-07-14 03:23 UTC, samfundev approved these changes

2023-07-14 03:23 UTC, samfundev commented
Thanks for the PR!

2023-07-14 03:23 UTC, merged