manual command - allows lookup of manual outside bomb
samfundev/KtaneTwitchPlays pull request #613
Opened 2023-08-07 21:04 UTC by red031000

2023-08-12 04:58 UTC, samfundev requested changes

2023-08-12 04:58 UTC, samfundev commented on TwitchPlaysAssembly/Src/Commands/GlobalCommands.cs
> +			IRCConnection.SendMessage($"Sorry, there is more than one module matching your search term. They are: {moduleInformation.Take(5).Select(x => $"“{x.moduleDisplayName}”").Join(", ")}");
This code seems very similar to the `.Search` extension. Could this be implemented using that instead?

2023-08-12 22:09 UTC, red031000 commented
changes made

2023-09-05 01:01 UTC, samfundev approved these changes

2023-09-05 01:02 UTC, merged